package com.drsecuritygps.app.ui.theme

import androidx.compose.ui.graphics.Color

val AppBg = Color(0xFFF3F3F3)
val AppPrimary = Color(0xFF58A8E0)
val AppPrimaryAlt = Color(0xFF50A8E0)
val AppCard = Color(0xFFFFFFFF)
val AppPanel = Color(0xFFF3F3F3)
val AppMuted = Color(0xFF7A7A7A)
val AppText = Color(0xFF222222)
val AppDanger = Color(0xFFEA5954)
val AppWarning = Color(0xFFF89818)
val AppSuccess = Color(0xFF48A850)
val AppSurfaceSoft = Color(0xFFF7F7F7)
val AppSurfaceMuted = Color(0xFFEEEEEE)
val AppTextOnPrimary = Color(0xFFFFFFFF)
val AppBorderLight = Color(0xFFE6E6E6)
val AppDivider = Color(0xFFECECEC)
val AppPrimaryLight = Color(0xFFEAF4FD)
val AppPrimarySoft = Color(0xFFD9EDF9)
val AppPurple = Color(0xFFAE59D9)
val AppPurpleLight = Color(0xFFF4EAFB)
val AppSuccessLight = Color(0xFFEAF7EC)
val AppWarningLight = Color(0xFFFFF3DD)
val AppDangerLight = Color(0xFFFDEAEA)
val AppIconGray = Color(0xFF6F6F6F)
val AppChevronGray = Color(0xFFB8B8B8)
val AppDarkChip = Color(0xFF6D7178)
